# Generated by Django 5.0.6 on 2024-05-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='Projets/Main')),
                ('title', models.CharField(max_length=2555)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.ImageField(upload_to='Users')),
                ('lastname', models.CharField(max_length=2555)),
                ('name', models.CharField(max_length=2555)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.IntegerField()),
                ('job_title', models.CharField(max_length=255)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=2555, null=True)),
                ('github_url', models.CharField(blank=True, max_length=2555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Projets/Photos')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Home.projet')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='tags',
            field=models.ManyToManyField(related_name='projets', to='Home.tag'),
        ),
        migrations.AddField(
            model_name='projet',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='projets', to='Home.utilisateur'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Projets/Videos')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Home.projet')),
            ],
        ),
    ]
